export const INIT_CALENDAR = "CALENDAR/INIT_CALENDAR";
export const NEXT_MONTH = "CALENDAR/NEXT_MONTH";
export const PREVIOUS_MONTH = "CALENDAR/PREVIOUS_MONTH";
export const SELECT_WEEK = "CALENDAR/SELECT_WEEK";
export const SELECT_DAY = "CALENDAR/SELECT_DAY";
export const SELECT_MONTH = "CALENDAR/SELECT_MONTH";