export const INIT_CALENDAR = "CALENDAR/INIT_CALENDAR";
export const NEXT_MONTH = "CALENDAR/NEXT_MONTH";
export const PREVIOUS_MONTH = "CALENDAR/PREVIOUS_MONTH";
export const SELECT_WEEK = "CALENDAR/SELECT_WEEK";
export const SELECT_DAY = "CALENDAR/SELECT_DAY";
export const SELECT_MONTH = "CALENDAR/SELECT_MONTH";


export const FETCH_USERS = "USERS/FETCH_USERS";
export const FETCH_USERS_FAIL = "USERS/FETCH_USERS_FAILED";
export const FETCH_USERS_SUCCESS = "USERS/FETCH_USERS_SUCCESS";


export const FETCH_USER_TIMESHEET = "USERS/FETCH_USER_TIMESHEET";
export const FETCH_USER_TIMESHEET_FAIL = "USERS/FETCH_USER_TIMESHEET_FAILED";
export const FETCH_USER_TIMESHEET_SUCCESS = "USERS/FETCH_USER_TIMESHEET_SUCCESS";

export const SELECT_LOGGED_IN_USER = "USER/SELECT_LOGGED_IN_USER";
export const SELECT_USER_TO_APPROVE = "USER/SELECT_USER_TO_APPROVE";


export const UPDATE_TIMESHEET_AFTER_ACTION = "USERS/UPDATE_TIMESHEET_AFTER_ACTION";